# the source is https://raw.githubusercontent.com/zakkg3/ClusterSecret/master/yaml/01_crd.yaml
# A demo CRD for the Kopf example operators.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clustersecrets.clustersecret.io
spec:
  scope: Namespaced
  group: clustersecret.io
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: ClusterSecret
    plural: clustersecrets
    singular: clustersecret
    shortNames:
      - csec
  additionalPrinterColumns:
    - name: Type
      type: string
      priority: 0
      JSONPath: .type
      description: Secret Type
